### ISSUE TITLE
SX1509 V11 Proto Checklist Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/SX1509_IO-Expander#2]
(1) I would like to see a paste (TCream) reduction on the SX1509 outer pads (center pad looks good). As it stands, the apertures for the outer pads cover the entire pad, I think it would be beneficial to reduce these apertures by 25-50%. Ideally, I would like to see paste applied to the portion of the pads that is covered by the IC, and nothing more.

I looked at the yields for past batches, and it appears that all of the rework was due to jumpers on the SX1509 IC.

(2) I noticed some BStop objects around the IC (2) and one object around the pin_1 and pin_2 through-holes. As it stands there will be some exposed copper on the bottom.

**Comment by jimblom** [comment]
1. Good call. I pulled the paste back into the edge of the pad - about a 50% reduction.
2. Phew, good catch. Deleted those.

**Comment by ericorosel** [comment]
(1) The IC FP looks awesome! The TCream reduction is perfect.

(2) I'm still seeing 1 object/segment of BStop on the bottom. Copper won't be exposed, but there will be a "Hole" on the solder mask. I attached a pic.

![sx1509_bob_1](https://cloud.githubusercontent.com/assets/3160317/7323113/92b6004a-ea69-11e4-906e-d8cc285e6869.png)

**Comment by jimblom** [comment]
Deleted. Thanks Eric!
