### ISSUE TITLE
multiple sx1509?

### ISSUE THREAD

**Issue by sqrtmo** [sparkfun/SX1509_IO-Expander#4]
Hello, 
I need to connect 4 SX1509 to arduino and to use it like a keyboard. I've tried with "sx1509_keypad" example and I've created different objects for every single expander. 
The init function gives me one for every single on startup, but I am getting strange behavior. Some times when I upload I have output from the buttons and some times not or I have only from one or two of them.
Can anyone help me?
Thanks in advance! 

This is the code I am using:

#include <Wire.h>
#include <sx1509_library.h>

const uint8_t run_led = 13;

//Addresses
const uint8_t ADDR_1 = 0x3E;
const uint8_t ADDR_2 = 0x70;
const uint8_t ADDR_3 = 0x3F;
// Arduino pin definitions
const uint8_t nRST_1 = 16;
const uint8_t nINT_1 = 17;

const uint8_t nRST_2 = 14;
const uint8_t nINT_2 = 15;

const uint8_t nRST_3 =  2;
const uint8_t nINT_3 =  3;

const uint8_t nRows = 8;
const uint8_t nCols = 8;

sx1509Class sx1( ADDR_1, nRST_1, nINT_1 );
sx1509Class sx2( ADDR_2, nRST_2, nINT_2 );
sx1509Class sx3( ADDR_3, nRST_3, nINT_3 );

void setup()
{
    Serial.begin(9600);
    
    // initialize the digital pin as an output.
    pinMode(run_led, OUTPUT);
    digitalWrite(run_led, LOW); // run led off
    
    delay(1000); // wait for serial monitor
    sxSetup_1();
    delay(500);
    sxSetup_2();
    delay(500);
    sxSetup_3();
}

//output variables
uint8_t R1, R1Prev;
uint8_t C1, C1Prev;

uint8_t R2, R2Prev;
uint8_t C2, C2Prev;

uint8_t R3, R3Prev;
uint8_t C3, C3Prev;
//end output variables

void loop()
{
    digitalWrite(run_led, HIGH);
    
    sx1_Probe();
//    if( C1 != C1Prev || R1 != R1Prev )
//    {
//        Serial.print("sx1 ");
//        Serial.print(R1);
//        Serial.println(C1);
//        
//    }
    delay(10);
    
    sx2_Probe();
//    if( C2 != C2Prev || R2 != R2Prev )
//    {
//        Serial.print("sx2 ");
//        Serial.print(R2);
//        Serial.println(C2);
//    }
    delay(10);
    
    sx3_Probe();
//    if( C3 != C3Prev || R3 != R3Prev )
//    {
//        Serial.print("sx3 ");
//        Serial.print(R3);
//        Serial.println(C3);
//    }
    delay(10);
    
    digitalWrite(run_led, LOW);
    
    R1Prev = R1;
    C1Prev = C1;
    
    R2Prev = R2;
    C2Prev = C2;
    
    R3Prev = R3;
    C3Prev = C3;
}
//----setup----
void sxSetup_1()
{
    int8_t x = sx1.init();
    
    if( x )
    {
        Serial.println("SX1 Init OK");
    } else {
        Serial.println("SX1 Init Failed");
    }
    
    sx1.configClock();
    
    byte sleepTime = 7;
    byte scanTime = 5; // Scan time per row <--<<<< 5 min for T3
    
    sx1.keypad(nRows, nCols, sleepTime, scanTime); // Advanced keypad init
    // We can also debounce the keypad inputs. The debounceConfig
    // method takes one parameter. Similar to the scanTime it's a
    // 3-bit value (0-7). This value must be <= scanTime!
    byte debounceTime = 1; // The debounce config value
    sx1.debounceConfig(debounceTime);
}

void sxSetup_2()
{
    int8_t x = 0;
    x = sx2.init();
    
    if( x )
    {
        Serial.println("SX2 Init OK");
        } else {
        Serial.println("SX2 Init Failed");
    }
    
    sx2.configClock();
    
    byte sleepTime = 7;
    byte scanTime = 5; // Scan time per row <--<<<< 5 min for T3
    
    sx2.keypad(nRows, nCols, sleepTime, scanTime); // Advanced keypad init
    // We can also debounce the keypad inputs. The debounceConfig
    // method takes one parameter. Similar to the scanTime it's a
    // 3-bit value (0-7). This value must be <= scanTime!
    byte debounceTime = 1; // The debounce config value
    sx2.debounceConfig(debounceTime);
}

void sxSetup_3()
{
    int8_t x = 0;
    x = sx3.init();
    
    if( x )
    {
        Serial.println("SX3 Init OK");
        } else {
        Serial.println("SX3 Init Failed");
    }
    
    sx3.configClock();
    
    byte sleepTime = 7;
    byte scanTime = 5; // Scan time per row <--<<<< 5 min for T3
    
    sx3.keypad(nRows, nCols, sleepTime, scanTime); // Advanced keypad init
    // We can also debounce the keypad inputs. The debounceConfig
    // method takes one parameter. Similar to the scanTime it's a
    // 3-bit value (0-7). This value must be <= scanTime!
    byte debounceTime = 1; // The debounce config value
    sx3.debounceConfig(debounceTime);
}
//-------------

void sx1_Probe()
{
    uint8_t out[2];
    
    static uint16_t keyData;
    static uint16_t previousKeyData = 0;
    static byte activeRow;
    static byte activeColumn;
    
    static uint16_t holdCount = 0;
    
    const uint8_t holdCountMax = 25;
    
    static uint16_t releaseCount = 0;
    static uint16_t releaseCountMax = 100;
    
    if (!digitalRead(nINT_1))
    {
        keyData = sx1.readKeyData();
        
        activeRow = keyData & 0xFF;
        activeColumn = keyData >> 8;
        
        activeRow = getBitPosition_1(activeRow);
        activeColumn = getBitPosition_1(activeColumn);
        
        if (keyData != previousKeyData)
        {
            holdCount = 0;
//            R1 = activeRow;
//            C1 = activeColumn;
                        Serial.print("sx1 ");
                        Serial.print(activeRow);
                        Serial.println(activeColumn);
        } else {
            holdCount++;
            if (holdCount > holdCountMax)
            {
//                R1 = activeRow;
//                C1 = activeColumn;
            }
        }
        
        releaseCount = 0;
        
        previousKeyData = keyData;
    }
    
    releaseCount++;
    if (releaseCount == releaseCountMax)
    {
        releaseCount = 0;
        previousKeyData = 0;
    }
}

void sx2_Probe()
{
    static uint16_t keyData;
    static uint16_t previousKeyData = 0;
    static uint8_t  activeRow;
    static uint8_t  activeColumn;
    
    static uint16_t holdCount = 0;
    
    const uint8_t   holdCountMax = 25;
    
    static uint16_t releaseCount = 0;
    static uint16_t releaseCountMax = 100;
    
    if ( !digitalRead(nINT_2) )
    {
        keyData = sx2.readKeyData();
        
        activeRow = keyData & 0xFF;
        activeColumn = keyData >> 8;
        
        activeRow = getBitPosition_2( activeRow );
        activeColumn = getBitPosition_2( activeColumn );
        
        if ( keyData != previousKeyData )
        {
            holdCount = 0;
//            R2 = activeRow;
//            C2 = activeColumn;
                        Serial.print("sx2 ");
                        Serial.print(activeRow);
                        Serial.println(activeColumn);
        } else {
            
            holdCount++; // Increment holdCount
            if ( holdCount > holdCountMax )
            {
//                R2 = activeRow;
//                C2 = activeColumn;
            }
        }
        releaseCount = 0;
        previousKeyData = keyData;
    }
    
    releaseCount++;
    
    if ( releaseCount == releaseCountMax )
    {
        releaseCount = 0;
        previousKeyData = 0;
    }
}

void sx3_Probe()
{
    static uint16_t keyData;
    static uint16_t previousKeyData = 0;
    static uint8_t  activeRow;
    static uint8_t  activeColumn;
    
    static uint16_t holdCount = 0;
    
    const uint8_t   holdCountMax = 25;
    
    static uint16_t releaseCount = 0;
    static uint16_t releaseCountMax = 100;
    
    if ( !digitalRead(nINT_3) )
    {
        keyData = sx3.readKeyData();
        
        activeRow = keyData & 0xFF;     //raboti kato keyData % 255
        activeColumn = keyData >> 8;    //???
        
        activeRow = getBitPosition_3( activeRow );
        activeColumn = getBitPosition_3( activeColumn );
        
        if ( keyData != previousKeyData )
        {
            holdCount = 0;
//            R3 = activeRow;
//            C3 = activeColumn;
                        Serial.print("sx3 ");
                        Serial.print(activeRow);
                        Serial.println(activeColumn);
        } else {
            
            holdCount++; // Increment holdCount
            if ( holdCount > holdCountMax )
            {
//                R3 = activeRow;
//                C3 = activeColumn;
            }
        }
        releaseCount = 0;
        previousKeyData = keyData;
    }
    
    releaseCount++;
    
    if ( releaseCount == releaseCountMax )
    {
        releaseCount = 0;
        previousKeyData = 0;
    }
}

byte getBitPosition_1( byte dataByte )
{
    for (byte i=0; i<8; i++)
    {
        if (dataByte & (1<<i))
        {
            return i;
        }
    }
    return 255; // Otherwise return an error
}

byte getBitPosition_2( byte dataByte )
{
    for (byte i=0; i<8; i++)
    {
        if (dataByte & (1<<i))
        {
            return i;
        }
    }
    return 255; // Otherwise return an error
}

byte getBitPosition_3( byte dataByte )
{
    for (byte i=0; i<8; i++)
    {
        if (dataByte & (1<<i))
        {
            return i;
        }
    }
    return 255; // Otherwise return an error
}

**Comment by s22e** [comment]
Bhhh.. It works perfect when I upload with Adruino 1.0.2. With the current version 1.6.3 it makes problems!

**Comment by ToniCorinne** [comment]
There was a big change in the library structure between 1.0.2 and 1.6.x on Arduino. We've updated the library, so try your code with the new library structure and see if that fixes the issue you're having.

**Comment by s22e** [comment]
thanks for the replay! hmm the old lib seems to work fine with newest 1.6.4 too..

**Comment by ToniCorinne** [comment]
Closing this issue out as it appears to be an issue with 1.6.3. Please reopen if you are still having issues.
